# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Set working directory
WORKDIR /app

# Copy package files
COPY package.json package-lock.json ./

# Install dependencies (ignoring scripts to avoid unwanted prepare scripts)
RUN npm install --ignore-scripts

# Copy the rest of the source code
COPY . .

# Build the project
RUN npm run build

# Expose any port if necessary; though MCP typically communicates over stdio
# ENV PORT=3000

# Start the MCP server
CMD ["npm", "start"]
